core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('csvs.urls')),
    path('', include('customers.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csvs/urls.py
from django.urls import path

from . import views

app_name='csv'

urlpatterns = [
    path('upload', views.upload_file, name='upload_file'),
]

customers/urls.py
from django.urls import path

from . import views

app_name='customer'

urlpatterns = [
    path('customer', views.customer_corr_view, name='customer-view'),
]

products/urls.py
from django.urls import path

from . import views


app_name='product'

urlpatterns = [
    path('', views.index, name='home'),
    path('add', views.add_purchase_view, name='add'),
    path('sales', views.sales_dist_view, name='sales')
]

csvs/models.py
from django.db import models

# Create your models here.

class Csv(models.Model):
    file_name = models.FileField(upload_to='documents/', max_length=100)
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'File id: {self.id}'

customers/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    company_name = models.CharField(max_length=220)
    budget = models.PositiveIntegerField()
    employment = models.PositiveIntegerField()
    joined = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.company_name

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=220)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name


class Purchase(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, null=True, blank=True)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    total_price = models.PositiveIntegerField(blank=True)
    salesman = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.total_price = self.price * self.quantity
        super(Purchase, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.product.name} - {self.price}'

csvs/forms.py
from django import forms

from .models import Csv


class CsvForm(forms.ModelForm):

    class Meta:
        model= Csv
        fields = ('file_name',)

products/forms.py
from django import forms
from .models import Product, Purchase


class PurchaseForm(forms.ModelForm):
    product = forms.ModelChoiceField(
        queryset=Product.objects.all(), 
        label='Product', 
        widget=forms.Select(
            attrs={'class': 'ui selection dropdown field-width'}))

    class Meta:
        model = Purchase
        fields = ['product', 'price', 'quantity']

csvs/views.py
import csv
from django.shortcuts import render
from django.contrib.auth.models import User

from .forms import CsvForm
from .models import Csv
from products.models import Purchase, Product

# Create your views here.


def upload_file(request):
    message = None
    error_message = None
    success_message = None
    if request.method == 'POST':
        form = CsvForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            form.save()
            try:
                
                file = Csv.objects.get(activated=False)

                with open(file.file_name.path, 'r') as f:
                    reader = csv.reader(f)

                    for row in reader:
                        row = ''.join(row)
                        row = row.replace(';', ' ')
                        row = row.split()
                        user = User.objects.get(id=row[3])
                        prod, _ = Product.objects.get_or_create(name=row[0])
                        
                        Purchase.objects.create(
                            product=prod,
                            price=int(row[2]),
                            quantity=int(row[1]),
                            salesman=user,
                            date=row[4] + ' ' + row[5])

                file.activated = True
                file.save()
                success_message = 'Upload sucessfully!'
            except Exception as exce:
                error_message = 'Ops. Something went wrong...'

    context = {
        'error_message': error_message,
        'success_message': success_message,
        'form': CsvForm(),
    }

    return render(request, 'upload_file.html', context)

customers/views.py
import pandas as pd
import seaborn as sns
from django.shortcuts import render
from matplotlib import pyplot

from .models import Customer
from products.utils import get_image


def customer_corr_view(request):
    df = pd.DataFrame(Customer.objects.all().values())
    corr = round(df['budget'].corr(df['employment']), 2)

    pyplot.switch_backend('Agg')
    sns.jointplot(x='budget', y='employment', kind='reg', data=df).set_axis_labels(
        'Company budget', 'No of employees')
    graph = get_image()
    context = {
        'graph': graph,
        'corr': corr
    }

    return render(request, 'customers.html', context)

products/views.py
import pandas as pd
import seaborn as sns
from matplotlib import pyplot

from django.shortcuts import render
from django.http import HttpResponse

from .models import Product, Purchase
from .utils import get_simple_plot, get_salesman_by_id, get_image
from .forms import PurchaseForm


def sales_dist_view(request):
    df = pd.DataFrame(Purchase.objects.all().values())
    df['salesman_id'] = df['salesman_id'].apply(get_salesman_by_id)
    df.rename({'salesman_id': 'salesman'}, axis=1, inplace=True)
    df['date'] = df['date'].apply(lambda x: x.strftime('%Y-%m-%d'))
    pyplot.switch_backend('Agg')
    pyplot.xticks(rotation=45)
    sns.barplot(x='date', y='total_price', hue='salesman', data=df)
    pyplot.tight_layout()
    graph = get_image()

    return render(request, 'sales.html', {'graph': graph})


def index(request):
    print(request.POST)
    graph = None
    error_message = None
    df = None
    price = None

    try:
        product_df = pd.DataFrame(Product.objects.all().values())
        purchase_df = pd.DataFrame(Purchase.objects.all().values())
        product_df['product_id'] = product_df['id']

        if purchase_df.shape[0] > 0:
            df = pd.merge(purchase_df, product_df, on='product_id').drop(
                ['id_y', 'date_y'], axis=1).rename({'id_x': 'id', 'date_x': 'date'}, axis=1)
            price = df['price']
            if request.method == 'POST':
                chart_type = request.POST.get('sales')
                date_from = request.POST['date_from']
                date_to = request.POST['date_to']
                print(chart_type)
                df['date'] = df['date'].apply(lambda x: x.strftime('%Y-%m-%d'))
                df2 = df.groupby('date', as_index=False)[
                    'total_price'].agg('sum')

                if chart_type != "":
                    if date_from != "" and date_to != "":
                        df = df[(df['date'] > date_from)
                                & (df['date'] < date_to)]
                        df2 = df.groupby('date', as_index=False)[
                            'total_price'].agg('sum')

                    graph = get_simple_plot(
                        chart_type, x=df2['date'], y=df2['total_price'], data=df)
                else:
                    error_message = 'Please select a chart type to continue'
        else:
            error_message = 'No records in the database'

    except:
        product_df = None
        purchase_df = None
        error_message = 'No records in the database'
    context = {
        'price': price,
        'graph': graph,
        'error_message': error_message,
    }

    return render(request, 'main.html', context)


def add_purchase_view(request):
    added_message = None
    if request.method == 'POST':
        form = PurchaseForm(request.POST or None)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.salesman = request.user
            obj.save()
            added_message = 'The purchase has been added'
        else:
            added_message = 'Error form'

    context = {
        'message': added_message,
        'form': PurchaseForm()
    }
    return render(request, 'add.html', context)

csvs/templates/upload_file.html
{% extends 'base.html' %}

{% block title %}Upload file{% endblock title %}


{% block content %}

{% if success_message %}
    <div class="ui success message">
        <i class="close icon"></i>
        <div class="header">
            {{ success_message }}
        </div>
    </div>
{% endif %}

{% if error_message %}
    <div class="ui negative message">
        <i class="close icon"></i>
        <div class="header">
            {{ error_message }}
        </div>
    </div>
{% endif %}


<h1>Upload file</h1>
<form action="" method="post" enctype="multipart/form-data" class="ui form">
    {% csrf_token %}

    {{ form }}

    <button type="submit" class="ui positive button mtop">Add data</button>
</form>

{% endblock content %}

customers/templates/customers.html
{% extends 'base.html' %}

{% block title %}Customers data{% endblock title %}


{% block content %}

<h1> Correlation: {{corr}} </h1>


{% if graph %}
<div class="block-center">
    <img src="data:image/png;base64, {{graph|safe}}" height="800" width="auto" />
</div>
{% endif %}
    

{% endblock%}

products/templates/add.html
{% extends 'base.html' %}

{% block title %}Add Purchase{% endblock title %}


{% block content %}

{% if message %}
    <div class="ui success message">
        <i class="close icon"></i>
        <div class="header">
            {{ message }}
        </div>
    </div>
{% endif %}



<form action="" method="post" class="ui form">
    {% csrf_token %}

    {{ form }}

    <button type="submit" class="ui positive button mtop">Add sales data</button>
</form>

{% endblock content %}

products/templates/main.html
{% extends 'base.html' %}

{% block title %}Products{% endblock title %}


{% block content %}

    <div class="ui modal mymodal">
        <div class="header">
            <h1>Price Data</h1>
        </div>
        <div class="ui container">
            <ul>
                <li><strong>Count:</strong> {{price.count}}</li>
                <li><strong>Mean:</strong> {{price.mean|floatformat}}</li>
                <li><strong>Medain:</strong> {{price.median}}</li>
                <li><strong>Min:</strong> {{price.min}}</li>
                <li><strong>Max:</strong> {{price.max}}</li>
                <li><strong>Std dev:</strong> {{price.std|floatformat}}</li>
            </ul>
        </div>
    </div>


    <h1>Dataframe</h1>
    <div>
    <div class="block-center">
        
            {% if error_message %}
            <div class="ui red message">
               <i class="close icon"></i>
                <div class="header">
                    {{ error_message }}
                </div>
            </div>
            {% endif %}

        
            {% if request.POST %}
                {% if graph %}
                    <img src="data:image/png;base64, {{ graph | safe }}">      
                {% endif %}
            {% endif %}
        </div>
            
       <form action="" method="POST" class="ui form mtop">
        {% csrf_token %}
        <div class="field">
            <label>Choose a chart type: </label>
            <div class="ui selection dropdown">
                <input type="hidden" name="sales">
                <i class="dropdown icon"></i>
                <div class="default text">----</div>
                <div class="menu">
                    <div class="item" value="bar">Bar plot</div>
                    <div class="item" value="line">Line plot</div>
                    <div class="item" value="count">Count plot</div>
                </div>
            </div>
        </div>
        <div class="field">
            <div class="two fields">
                <div class="field">
                    <label>Date from: </label>
                    <input type="date" name="date_from">
                </div>
                <div class="field">
                    <label>Date to: </label>
                    <input type="date" name="date_to">
                </div>
            </div>
        </div>
        <div class="block-center">
            <button class='ui primary button' type='submit'>Select</button>
        </div>
    </form>
    <div class="block-center">
        <button type="button" class="ui secondary button button-btn">See Summary</button>
         <br>
        <a href="{% url 'product:add' %}"><button class='ui positive button'>Add records</button></a>
    </div>
    </div>

{% endblock content %}

products/templates/sales.html
{% extends 'base.html' %}

{% block title %}Sales{% endblock title %}


{% block content %}
<h1>Sales</h1>
{% if graph %}
    <div class="block-center">
        <img src="data:image/png;base64, {{graph|safe}}" height="800" width="auto" />
    </div>
{% endif %}    

{% endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{% block title %} DataScience {% endblock title %}</title>

    <!-- jQuery -->

    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <!-- semantic UI -->
    <link rel="stylesheet"type="text/css" href="{% static 'css/semantic.min.css' %}"/>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="ui container">
      {% block content %} {% endblock content %}

      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script> {% endcomment %}
      <script src="{% static 'js/semantic.min.js' %}"></script>
      <script src="{% static 'js/script.js' %}"></script>
    </div>
  </body>
</html>

templates/navbar.html
{% url 'product:home' as path_to_home %}
{% url 'product:add' as path_to_add %}
{% url 'product:sales' as path_to_sales %}
{% url 'csv:upload_file' as path_to_upload_file %}
{% url 'customer:customer-view' as path_to_customer %}



<div class="ui secondary pointing menu">
  <a href="{% url 'product:home' %}" class="item">
    Home
  </a>

  <a href="{{path_to_home}}"  class="item {% if request.path == path_to_home %}active{% endif %}">
    Performance
  </a>
  <a href="{{path_to_sales}}" class="item {% if request.path == path_to_sales %}active{% endif %}">
    Sales
  </a>
  <a href="{{ path_to_customer }}" class="item {% if request.path == path_to_customer %}active{% endif %}">
    Customers
  </a>
  <a href="{{ path_to_add }}" class="item {% if request.path == path_to_add %}active{% endif %}">
    Add records
  </a>
   <a href="{{ path_to_upload_file }}" class="item {% if request.path == path_to_upload_file %}active{% endif %}">
    Upload file
  </a>
  
  <div class="right menu">
     <a href="#" class="item">
      Login
    </a>
  </div>

</div>